name: CI

on: [push, pull_request]

jobs:

  build-ubuntu:
    runs-on: ubuntu-22.04
    steps:

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Dependency packages (apt)
      run: |
        sudo apt update
        sudo apt -y install git gcc-arm-none-eabi python3-pip srecord zip

    - name: Dependency packages (pip)
      run: python3 -m pip install crcmod intelhex setuptools_scm

    - name: Build dist
      run: |
        make -j4 dist
        echo ver=$(make version) >> $GITHUB_ENV

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: samisara.ci.${{ env.ver }}
        path: out/*.zip
